variables:
- group: "production"
- name: API_URL
  value: $apiUrl

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - app

pool:
  vmImage: windows-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'app'
- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    workingDir: 'app'
    customCommand: 'run build'
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'app/dist/*'
    azureSubscription: '$(azureSubscription)'
    Destination: 'AzureBlob'
    storage: '$(storageAccountName)'
    ContainerName: '$web'
