variables:
- group: "production"

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - api

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'api/src/*.csproj'
    arguments: '--configuration Release'
- task: AzureFunctionApp@1
  displayName: 'deploy azure function app'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'functionAppLinux'
    appName: '$(functionAppName)'
    package: '$(System.DefaultWorkingDirectory)/api/src/**/*.zip'
    runtimeStack: 'DOTNET|3.1'
